### ISSUE TITLE
Error: Tapo(InvalidCredentials)

### ISSUE THREAD

**Issue by khandieyea** [mihai-dinculescu/tapo#111]
Hey,

Been trying to figure out how best to get access to my P110s to pull energy stats.
Paraphrasing off the internet here - something changed in the TAPO firmware at some point in the past and now most API implementations no longer work. 
Does your API client still work on the latest firmware? (v1.2.3)

The part I can't figure out is I've never once set credentials for the device itself, so I can only assume it's the same as my TAPO Account. But still InvalidCredential.

tia

**Comment by mihai-dinculescu** [comment]
Yes, it does work with firmware 1.2.3.

You are correct. The e-mail and the password combination are the ones of your TP-Link account.

Your device needs to connect to the internet on the initial setup and after every TP-Link password change so that it gets synced. Outside these two situations, you can keep your device off the internet.

Some people got the invalid credentials error a while back because they had upper-case letters in their TP-Link e-mail. The fix for them was either to ensure they got the capitalisation right or to re-create their accounts with a lower-case e-mail.

**Comment by khandieyea** [comment]
Ah! Thanks for this! The whole reset password after adding device.

Cheers!
