### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by merbanan** [mihai-dinculescu/tapo#70]
I get:
error: package `time v0.3.19` cannot be built because it requires rustc 1.62.0 or newer, while the currently active rustc version is 1.61.0

Is it possible to depend on an earlier time package version ? Building on Ubuntu 22.04.2 LTS fails.

**Comment by mihai-dinculescu** [comment]
Is there a reason why you cannot upgrade your rust compiler? I've had no problem installing 1.67 on Ubuntu **20**.04.5 LTS.

**Comment by merbanan** [comment]
Well my rust skills are limited. Anyways
curl https://sh.rustup.rs -sSf | sh
source "$HOME/.cargo/env"
gave me an updated environment.

**Comment by merbanan** [comment]
Now I just need to find the device on the network.

**Comment by mihai-dinculescu** [comment]
I'm glad that upgrading the rust version has solved the problem. Because of the non-breaking nature of the rust releases, there's rarely a justification to support old versions. The general consensus is that, in most cases, people should try and use a recent version due to the benefits they bring.

The Tapo mobile app has a "Device Info" section that shows the IP of each device.
Of course, if you want it to be resilient (e.g. the IP not to change on router/device restarts), you will need to make the IP static in your router configuration.
